name: qcarchive
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - msgpack-python>=0.6.1
  - pandas
  - tornado
  - requests
  - bcrypt
  - cryptography
  - pyyaml>=5.1
  - pydantic>=0.30.1
  - plotly
  - sqlalchemy>=1.3
  - psycopg2>=2.7
  - postgresql
  - alembic
  - tqdm

# Test depends
  - pytest
  - pytest-cov
  - codecov

# QCArchive includes
  - qcengine>=0.9.0
  - qcelemental>=0.7.0
