name: qcarchive
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - mongodb
  - pymongo
  - tornado
  - requests
  - jsonschema
  - bcrypt
  - cryptography

# Test depends
  - pytest
  - pytest-cov
  - codecov

# QCArchive includes
  - qcengine>=0.4.0
  - qcelemental>=0.1.3

# Pip includes
  - pip:
    - pydantic
    - mongoengine
