name: qcarchive
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - mongodb
  - pymongo
  - tornado
  - requests
  - bcrypt
  - cryptography
  - pydantic
  - mongoengine
  - sqlalchemy
  - psycopg2
  - sqlalchemy_utils
  - plotly

# Test depends
  - pytest
  - pytest-cov
  - codecov

# QCArchive includes
  - qcengine>=0.6.2
  - qcelemental>=0.3.1
