name: qcarchive
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - mongodb
  - pymongo
  - tornado
  - requests
  - bcrypt
  - cryptography
  - pydantic

# Test depends
  - pytest
  - pytest-cov
  - codecov

# QCArchive includes
  - qcengine>=0.5.1
  - qcelemental>=0.2.5

# Pip includes
  - pip:
    - mongoengine
