name: qcarchive
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - msgpack-python>=0.6.1
  - pandas
  - tornado
  - requests
  - bcrypt
  - cryptography
  - pyyaml>=5.1
  - pydantic>=1.0.0
  - plotly>=4.0.0
  - sqlalchemy>=1.3
  - psycopg2>=2.7
  - postgresql
  - alembic
  - tqdm
  - h5py
  - pyarrow>=0.13.0
  - double-conversion>=3.0.0

# Test depends
  - pytest
  - pytest-cov
  - codecov
  - requests-mock

# QCArchive includes
  - qcengine>=0.11.0
  - qcelemental>=0.9.0
