# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
 
dist: trusty

matrix:
  include:
    - os: linux
      python: 3.5
      env: PYTHON_VER=3.5
    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6

before_install:
  # Additional info about the build
  - uname -a
  - free -m
  - df -h
  - ulimit -a

  # Setup python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Create test environment for package
  - conda create -q -n test_env python=$PYTHON_VER numpy nomkl pandas pymongo pytest tornado requests psi4=1.2rc2 -c psi4/label/dev
  - source activate test_env
  - conda install codecov pytest-cov jsonschema -c conda-forge

    # Install anything not in conda
#  - pip install fireworks

    # Install the latest qcengine for testing
  - pip install git+git://github.com/MolSSI/QCEngine#egg=qcengine

    # Build and install package
  - python setup.py develop --no-deps
#  - conda build --python=$PYTHON_VER devtools/conda-recipe
#  - conda install --yes --use-local project_name

before_script:
  - sleep 5
  - python -V
  - mongod --version
  - conda list

script:
  - py.test -v --cov=qcfractal qcfractal/

notifications:
  email: false

after_success:
  - codecov

