# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

services:
  - mongodb

python:
    - 2.7
    - 3.5
    - 3.6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
    # Cache Miniconda
  - cd
  - mkdir -p download
  - cd download
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n mongo_qcdb python=$TRAVIS_PYTHON_VERSION numpy pandas pymongo pytest matplotlib dask distributed
  - source activate mongo_qcdb

    # Install anything not in conda
  - pip install codecov
  - pip install pytest-cov
  - conda list
  - mongod --version

before_script:
  - sleep 5
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'
  - pip install -e .
  - export MONGO_PSI4=/tmp/

script:
  - py.test -v --cov=./

cache:
  apt: true
  directories:
    - $HOME/cache
    - $HOME/.cache/pip
    - $HOME/download

notifications:
  email: false

after_success:
  - codecov

