# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

services:
  - mongodb


matrix:
  include:
    - python: 2.7
      env: PYTHON_VER=2.7
      addons: &1
        apt:
          sources:
          - mongodb-3.0-precise
          packages:
          - mongodb-org-server
    - python: 3.5
      env: PYTHON_VER=3.5
      addons: &2
        apt:
          sources:
          - mongodb-3.0-precise
          packages:
          - mongodb-org-server

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - if [[ "$PYTHON_VER" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n mongo_qcdb python=$PYTHON_VER numpy pandas pymongo pytest matplotlib dask distributed
  - source activate mongo_qcdb
  - pip install codecov
  - pip install pytest-cov
  - conda list
  - mongod --version

before_script:
  - sleep 5
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'
  - pip install -e .
  - export MONGO_PSI4=/tmp/

script:
  - py.test -v --cov=./

cache:
  directories:
    - $HOME/cache
before_cache:
  # Remove all untarred directories.
  - find $CONDA_INSTALL_LOCN/pkgs/ -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;

notifications:
  email: false

after_success:
  - codecov

