# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
 
dist: trusty

matrix:
  include:
    - os: linux
      python: 3.5
      env: PYTHON_VER=3.5
    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6

before_install:
  # Additional info about the build
  - uname -a
  - free -m
  - df -h
  - ulimit -a

  # Setup python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Create test environment for package
  - conda create -q -n --yes dqm_env python=$PYTHON_VER numpy pandas pymongo pytest
  - source activate dqm_env

    # Install dqm_client from a tagged version
  - pip install git+https://github.com/MolSSI/dqm_client

    # Install anything not in conda
#  - pip install fireworks
  - pip install codecov pytest-cov

    # Build and install package
  - pip install -e .
#  - conda build --python=$PYTHON_VER devtools/conda-recipe
#  - conda install --yes --use-local project_name

before_script:
  - sleep 5
  - python -V
  - mongod --version
  - conda list

script:
  - py.test -v --cov=dqm_server tests/

notifications:
  email: false

after_success:
  - codecov

