cluster:
  adaptive: adaptive
  node_exclusivity: false
  scheduler: null
  scheduler_options: []
  task_startup_commands: []
  walltime: 06:00:00
common:
  adapter: pool
  cores_per_rank: 1
  cores_per_worker: 4
  max_workers: 1
  memory_per_worker: 5.508
  nodes_per_job: 1
  nodes_per_task: 1
  retries: 2
  scratch_directory: null
  tasks_per_worker: 1
  verbose: false
dask:
  extra: null
  interface: null
  lsf_units: null
manager:
  log_file_prefix: null
  manager_name: unlabeled
  max_queued_tasks: null
  ntests: 5
  queue_tag: null
  test: false
  update_frequency: 30.0
parsl:
  executor:
    address: null
  provider:
    launcher: null
    partition: null
server:
  fractal_uri: localhost:7777
  password: null
  username: null
  verify: null
