name: qcfractal-docs
channels:
    - defaults
dependencies:
    - python=3.6
    - numpy
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
    - graphviz

    - pip:
      - git+git://github.com/MolSSI/qcarchive-sphinx-theme#egg=qcarchive_sphinx_theme
